- type: technology
  id: RiotControl
  name: ataraxia-research-technology-riot-control
  icon:
    sprite: Objects/Weapons/Guns/Battery/particle_decelerator.rsi
    state: base
  discipline: RiotControl
  tier: 1
  cost: 7500
  recipeUnlocks:
  - WeaponParticleDecelerator
  - HoloprojectorField

- type: technology
  id: RiotControlAdvanced
  name: ataraxia-research-technology-riot-control-advanced
  icon:
    sprite: Objects/Weapons/Melee/truncheon.rsi
    state: icon
  discipline: RiotControl
  tier: 1
  cost: 8000
  recipeUnlocks:
  - Truncheon
  - TelescopicShield
  - HoloprojectorSecurity
  - WeaponDisablerSMG
  technologyPrerequisites:
  - RiotControl

#- type: technology # Because need port
#  id: GripsLightweight
#  name: ataraxia-research-technology-grips-lightweight
#  icon:
#    sprite: White/MagGloves/maggloves.rsi
#    state: icon
#  discipline: GripsGloves
#  tier: 1
#  cost: 7500
#  recipeUnlocks:
#    - ClothingHandsGlovesMagnetic

#- type: technology # Because need port
#  id: GripsAdvanced
#  name: ataraxia-research-technology-grips-advanced
#  icon:
#    sprite: White/MagGloves/magglovesadvanced.rsi
#    state: icon
#  discipline: GripsGloves
#  tier: 1
#  cost: 10000
#  recipeUnlocks:
#    - ClothingHandsGlovesMagneticAdvanced
#  technologyPrerequisites:
#  - GripsLightweight
